### ISSUE TITLE
System.UnauthorizedAccessException:“(5) 拒绝访问

### ISSUE THREAD

**Issue by zoujiepro** [alphaleonis/AlphaVSS#39]
When I ran the sample code, an UnauthorizedAccessException exception occurred。Here are some error messages as follows：

System.UnauthorizedAccessException
  HResult=0x80070005
  Message=(5) 拒绝访问。: [\\?\GLOBALROOT\Device\HarddiskVolumeShadowCopy8\Windows\system32\config\sam]
  Source=AlphaFS
  StackTrace:
   at Alphaleonis.Win32.NativeError.ThrowException(UInt32 errorCode, String readPath, String writePath)
   at Alphaleonis.Win32.Filesystem.File.RestartCopyMoveOrThrowException(Int32 lastError, Boolean isFolder, Boolean isMove, KernelTransaction transaction, String sourcePathLp, String destinationPathLp, Nullable`1 moveOptions)
   at Alphaleonis.Win32.Filesystem.File.CopyMoveCore(KernelTransaction transaction, Boolean driveChecked, Boolean isFolder, String sourcePath, String destinationPath, Nullable`1 copyOptions, Nullable`1 moveOptions, Boolean preserveDates, CopyMoveProgressRoutine progressHandler, Object userProgressData, CopyMoveResult copyMoveResult, PathFormat pathFormat)
   at Alphaleonis.Win32.Filesystem.File.Copy(String sourcePath, String destinationPath)
   at VssSample.Examples.Example1() in D:\workSpace\visualStudio\AlphaVSS-Samples\src\VssBackup\Examples.cs:line 43
   at VssSample.Examples.Main(String[] args) in D:\workSpace\visualStudio\AlphaVSS-Samples\src\VssBackup\Examples.cs:line 16

**Comment by alphaleonis** [comment]
Does your user have permissions to read the specific file?  I'm guessing files there may require administrative privileges to read them.  I don't think this is related to AlphaVSS .

**Comment by zoujiepro** [comment]
I also suspected that the directory did not have permission, so I copied the sam file to the D drive, but the following error occurred. I just tried other files and found that it works. Thank you for your answer
